- src: https://github.com/mGageTechOps/ansible-role-cfn-ecs
  name: ecs
  version: 1.0.1

- src: https://github.com/mGageTechOps/ansible-role-cfn-ecs-task
  name: ecs_task
  version: 0.0.3

- src: https://github.com/mGageTechOps/ansible-role-cfn-ecs-service
  name: ecs_service
  version: 0.1.6
